### ISSUE TITLE
svg images?

### ISSUE THREAD

**Issue by jrochkind** [blocknotes/prawn-html#41]
[prawn-svg](https://github.com/mogest/prawn-svg) adds support for SVG images to prawn.  However, it does so by adding a new `svg` method to prawn, where you give it SVG source. 

I wonder if there's any sane way to combine that with prawn-html, such that HTML <img> tags can somehow point to SVGs....

Any thoughts?

**Comment by blocknotes** [comment]
Hey @jrochkind.
Thank you reporting this one, I don't know that gem.
I have just made a fast check, at this time I don't see an easy way to integrate it in _prawn-html_.

A workaround could be:

```rb
pdf = Prawn::Document.new(page_size: 'A4')
PrawnHtml.append_html(pdf, '<h1>before svg</h1>')
pdf.svg '<svg><rect width="100" height="100" fill="blue"></rect></svg>'
PrawnHtml.append_html(pdf, '<h1>after svg</h1>')
pdf.render_file('/tmp/test.pdf')
```

For some reason the svg takes the remaining of the page 🤔 
But I saw that it happens also with:

```rb
Prawn::Document.generate("test.pdf") do
  svg '<svg><rect width="100" height="100" fill="red"></rect></svg>'
  svg '<svg><rect width="100" height="100" fill="green"></rect></svg>'
end
```

So 🤷

**Comment by jrochkind** [comment]
OK, thanks. 

Splitting up into multiple `append_html` makes it harder to provide CSS in a `<style>` you need to provide it (and wrapping html/head/body tags) multiple times. 

But yeah, I don't see any great answer either. Although i guess code could be written. I'm not sure if I'm up for it, but would you be amenable to a PR?

**Comment by blocknotes** [comment]
You are right @jrochkind. And it could be a nice improvement also in other situations (ex. mixing other Prawn plugins).

I have just prepared a new PR here that could help: https://github.com/blocknotes/prawn-html/pull/43

The usage could be (if you can make a try on your side it would be great):

```rb
pdf = Prawn::Document.new(page_size: 'A4')
phtml = PrawnHtml::Instance.new(pdf)
phtml.append(html: '<h1>before svg</h1>')
pdf.svg '<svg><rect width="100" height="100" fill="blue"></rect></svg>'
phtml.append(html: '<h1>after svg</h1>')
pdf.render_file('/tmp/test.pdf')
```

BTW, if you want to try something in a PR you are welcome.

**Comment by blocknotes** [comment]
The merged PR should be enough for now. Closing
