### ISSUE TITLE
Exception raised when presented with `font-family: inherit`

### ISSUE THREAD

**Issue by padde** [blocknotes/prawn-html#45]
We are using quilljs for WYSIWYG editing of contents, that are later rendered into a PDF via prawn-html. Sometimes, this results in markup like this:

```html
<strong style="font-family: inherit">text</strong>
```

which results in the following error when rendering:

```ruby
Prawn::Errors::UnknownFont (inherit (normal) is not a known font.)
```

for other similar CSS directives such as `background-color: inherit;` there does not seem to be a problem.

Minimal reproducible example:

```ruby
require 'prawn-html'
pdf = Prawn::Document.new
PrawnHtml.append_html(pdf, '<strong style="font-family: inherit">text</strong>')
# Prawn::Errors::UnknownFont: inherit (normal) is not a known font.
```

**Comment by blocknotes** [comment]
Hey @padde 
Thank you for the issue.
The fix PR is ready and merged.
It will be available in the next release.

**Comment by blocknotes** [comment]
[Release 0.7.1](https://github.com/blocknotes/prawn-html/releases/tag/v0.7.1) ready ✅

**Comment by padde** [comment]
@blocknotes that's great news, thank you for your quick response and immediate fix 💛
