### ISSUE TITLE
how make image and text on one line

### ISSUE THREAD

**Issue by devifr** [blocknotes/prawn-html#50]
hi need your suggestion, how i can make image and text on same line, image always different line with text, 
for example i create 
`pdf = Prawn::Document.new(bottom_margin: 72)
PrawnHtml.append_html(pdf, '<p style="display:inline;"><img height="26" width="26" src="image_path" cc-icon-id="1">test</p>')`

the image and text not in same line, how i can make the text and image on same line?

**Comment by blocknotes** [comment]
Hey @devifr
At this time `prawn-html` doesn't support the _display_ property, but it would be pretty nice to have it so I'll take a look when possibile.

As a workaround I could suggest you to move text using position absolute, example:

```html
  <img src="some_image.jpg" style="width: 200px">
  <div style="position: absolute; left: 220px; top: 0px">Just some test on the right of the image.</div>
  <div>Some random content below the image.</div>
```
